modLoader="javafml"
loaderVersion="[43,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="ponder"
version="${file.jarVersion}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
authors="${mod_author}"
credits="${mod_credit}"
description='''
${mod_description}
'''

[[dependencies.ponder]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ponder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ponder]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10,0.6.11)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.ponder]]
    modId="catnip"
    mandatory=true
    versionRange="[0.6,)"
    ordering="AFTER"
    side="BOTH"
