modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
authors="${mod_author}"
credits="${mod_credit}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="flywheel"
mandatory=true
versionRange="${flywheel_version_range}"
ordering="AFTER"

[[dependencies.${mod_id}]]
modId="catnip"
mandatory=true
versionRange="${catnip_version_range}"
ordering="AFTER"
side="BOTH"
